import pandas as pd
configfile: "../config/config.yaml"
SAMPLES = pd.read_csv(config["sample_file"])['Sample']

include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/star.smk"
include: "rules/cufflinks.smk"
include: "rules/invert.smk"

ANNOT = config["annotations"]["combined"]

rule all:
    input: 
        expand("../results/invert/{sample}/{sample}_final_results.csv", sample=SAMPLES)




