#Config file to accompany invert snakemake pipeline


in_dir: data/ #Directory containing raw fastq files from RNAseq
annotation_file: ref_files/Homo_sapiens.GRCh38.103.gtf #Directory containing the viral host genome annotation in .gtf format
# genome_index: #Directory containing indices of each influenza 

parameters:
  illuminaclip: ["ILLUMINACLIP:ref_files/TruSeq3-PE-2.fa"] #Directory containing illumina adapter sequences that should be trimmed