#Config file to accompany invert snakemake pipeline

in_dir: data #Directory containing raw fastq files from RNAseq
samples: 4_12hr_Ciliated_4_S4_sample
annotations:
  combined: ref_files/cal09_human/GRCh38.103_Cal09.gtf #GTF file of concatenated virus + host genomes annotation
  iav_only: ref_files/cal09/IAV_Cal09.gtf #GTF file of virus ONLY annotation
  
ref_genome:
  combined: ref_files/cal09_human/GRCh38.103_Cal09.fa # reference genome of combined host + virus
  iav_only: ref_files/cal09/IAV_Cal09.fa

genome_index: "ref_files/cal09_human_star_index" #directory containin concatenated human+virus genome, indexed by STAR


parameters:
  trim: [ILLUMINACLIP:ref_files/TruSeq3-PE-2.fa:2:30:10 TRAILING:3] #Directory containing illumina adapter sequences that should be trimmed