#Conda environment file containing dependencies for INVERT snakemake pipeline

name: invert

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - snakemake =6.2.1
  - trimmomatic =0.36
  - snakemake-wrapper-utils =0.1.3
  - pigz =2.3.4
  - star =2.7.1a
  - fastqc =0.11.9
  - cufflinks=2.2.1
  - samtools