#Conda environment file containing dependencies for INVERT snakemake pipeline

name: invert

channels:
  - bioconda
  - conda-forge


dependencies:
  - trimmomatic==0.36
  - snakemake-wrapper-utils==0.1.3
  - pigz==2.3.4
  - star==2.5.3a
  - fastqc
  - snakemake-minimal >=5.24.1
