#Config file to accompany invert snakemake pipeline

in_dir: ../data #Directory containing raw fastq files from RNAseq
sample_file: ../config/samples.csv

trimmomatic: #Trimmomatic parameters
    threads: 32
    other: ILLUMINACLIP:../ref_files/all_illumina_adapters.fa:2:30:10  LEADING:10 TRAILING:10 SLIDINGWINDOW:4:20 MINLEN:38

annotations:
  combined: /path/to/combined/pr8-mdck.gtf #GTF file of concatenated virus + host genomes annotation
  
ref_genome:
  combined: /path/to/combined/pr8-mdck.fa # reference genome of combined host + virus

genome_index: "/path/to/pr8-mdck_index" #directory containin concatenated human+virus genome, indexed by STAR
