#Config file to accompany invert snakemake pipeline

in_dir: ../data #Directory containing raw fastq files from RNAseq
sample_file: ../config/samples.csv

trimmomatic: #Trimmomatic parameters
    threads: 32
    other: SLIDINGWINDOW:4:20

annotations:
  combined: /home/langlois/shared/ref_genomes/star_indices/pr8_mdck/PR8_MDCK.gtf #GTF file of concatenated virus + host genomes annotation
  iav_only: /home/langlois/shared/ref_genomes/star_indices/pr8_mdck/PR8.gtf #GTF file of virus ONLY annotation
  
ref_genome:
  combined: /home/langlois/shared/ref_genomes/star_indices/pr8_mdck/PR8_MDCK.fa # reference genome of combined host + virus
  iav_only: /home/langlois/shared/ref_genomes/star_indices/pr8_mdck/PR8.fasta

genome_index: "/home/langlois/shared/ref_genomes/star_indices/pr8_mdck/index" #directory containin concatenated human+virus genome, indexed by STAR

parameters:
  trim: [SLIDINGWINDOW:4:20 MINLEN:25] 
